"""create_tables

Revision ID: 23d04c850232
Revises: d17ca9b17a7f
Create Date: 2025-03-02 19:04:10.097928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d04c850232'
down_revision: Union[str, None] = 'd17ca9b17a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'notes')
    # ### end Alembic commands ###
